### ISSUE TITLE
C++ support is broke

### ISSUE THREAD

**Issue by mlfarrell** [wasdk/wasdk#4]
See here

https://wasdk.github.io/WasmFiddle/?17fp9j

**Comment by yurydelendik** [comment]
The generated wast looks good. You just need to provide dependencies required by std::string, e.g. _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev at imported `env` object . The stack pointer at offset 4 needs to be set as well. Closing as invalid since it's a limitation of wasmfiddle. It is/will be addressed by [wasmbase](https://github.com/wasdk/wasmbase)
